puts "The students of Villains Academy"
puts "_____________"
puts "Dr.Hannibal Lectar"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baraheon"
puts "Norman Bates"
